In [6]:
import pandas as pd

In [7]:
with open("./data/final_data.csv", "r", encoding="utf-8") as f:
    df = pd.read_csv(f, header=None)

df.tail()

,0,1,2,3,4
3873,3873,0.979017,Larry Flint won’t be the only citizen paying m...,1998-1999,gop
3874,3874,0.988775,"None of these subjects, however, had nearl...",1998-1999,gop
3875,3875,0.022600,Doing so could very well be the only hope for ...,1998-1999,gop
3876,3876,0.137158,While discussing potential GOP vice-presidenti...,1999-2000,gop
3877,3877,0.362278,“This country is dying for minority leadership...,1999-2000,gop

In [8]:
# adjusting sentiments such that 1 is most liberal and 0 is most conservative
#
#  issue            current                  needs flipped (y/n)
# abortion -> 1=liberal, 0=conservative             n
# welfare -> 1=liberal, 0=conservative              n
# bush -> 1=conservative, 0=liberal                 y
# clinton -> 1=liberal, 0=conservative              n
# dole -> 1=conservative, 0=liberal                 y
# affirmative_action -> 1=liberal, 0=conservative   n
# conservative -> 1=conservative, 0=liberal         y
# liberal -> 1=liberal, 0=conservative              n
# republican -> 1=conservative, 0=liberal           y
# democrat -> 1=liberal, 0=conservative             n
# gop -> 1=conservative, 0=liberal                  y

flipped_keywords = [
    'bush', 'dole', 'conservative', 'republican', 'gop'
]
val = 0
for i in range(len(df)):
    if df.iat[i, 4] in flipped_keywords:
        val = 1.0-float(df.iat[i,1])
        df.iat[i,1] = val

df.tail()

,0,1,2,3,4
3873,3873,0.020983,Larry Flint won’t be the only citizen paying m...,1998-1999,gop
3874,3874,0.011225,"None of these subjects, however, had nearl...",1998-1999,gop
3875,3875,0.977400,Doing so could very well be the only hope for ...,1998-1999,gop
3876,3876,0.862842,While discussing potential GOP vice-presidenti...,1999-2000,gop
3877,3877,0.637722,“This country is dying for minority leadership...,1999-2000,gop

In [9]:
#save DataFrame to .csv one last time, containing all data + weights
df.to_csv("./data/final_data_weighted.csv", index=False, header=False)